name: Slack Notification for MWSCUP Team
on:
  pull_request:
    branches:
      - main
  push:  # for test
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify to Slack Group
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: mws_2021
          SLACK_COLOR: green
          SLACK_TITLE: Pull Request
          SLACK_MESSAGE: ${{ github.event.head_commit.message }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/921/921513.png
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
