name: Slack notification for mws_2021
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify to Slack Group
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: mws_2021
          SLACK_COLOR: "good"
          SLACK_TITLE: ${{ github.event.pull_request.title }}
          SLACK_MESSAGE: ${{ github.event.pull_request.body }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1051/1051275.png
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
